name: CI
on :
 - push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run the Maven Verify phase
        run: mvn verify

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: artifact/menu-server.jar

  release:
    needs: [build]
    if: contains (github.ref,'refs/tags/v')
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: artifact/menu-server.jar

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: artifact/menu-server.jar
